Fixing Strings
Ericgacoki/safe-args pull request #2
Opened 2021-06-26 15:52 UTC by MaurineM

- [x] Duplicated some files
- [ ] Edited Code

This Fixes #1

2021-06-26 16:05 UTC, Ericgacoki reviewed
Hello @MaurineM, please go through my suggestions and make the respective corrections.

2021-06-26 16:05 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +
Please change the package name to match the parent directory

2021-06-26 16:05 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +               findNavController().navigate(action)
please explain why you did this!

2021-06-26 16:05 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +        }?.root
Root doesn't work like this!

2021-06-26 16:12 UTC, MaurineM commented
Hey @Ericgacoki, I've made the changes! Please check them out.

2021-06-26 16:15 UTC, Ericgacoki approved these changes
Hello @MaurineM, approved!

2021-06-26 16:19 UTC, Ericgacoki requested changes

2021-06-26 16:19 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +import com.demo.safeargs.databinding.FragmentABinding
Just noticed that the View class is implemented wrongly.

2021-06-26 16:22 UTC, Ericgacoki approved these changes

2021-06-26 16:24 UTC, Ericgacoki commented
Compatible but won't merge due to some reasons. We can still reopen this later. thank you!

2021-07-08 17:07 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +import com.demo.safeargs.databinding.FragmentABinding
Nice imports.

2021-07-10 13:11 UTC, Ericgacoki requested changes

2021-07-10 13:11 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +import android.view.View
```suggestion
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View1
```

2021-07-10 13:11 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +import com.demo.safeargs.databinding.FragmentABinding
```suggestion
import androidx.navigation.fragment.findNavController
import com.demo.safeargs.databinding.FragmentABinding 2
```

2021-07-10 13:11 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +        container: ViewGroup?,
```suggestion
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?, 3
```

2021-07-10 13:11 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.kt
> +    }
```suggestion
        }?.root
    }
```
remove roots

2021-07-10 13:13 UTC, Ericgacoki approved these changes

2021-07-13 21:43 UTC, Ericgacoki requested changes

2021-07-13 21:43 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.md
> +```
```suggestion
### Export JSON to MongoDB Database (commit 1)
Now let us export the new file to JSON using the following command:
```bash
mongoexport --db studentinfo --collection student --out d:\out.json
```
```

2021-07-13 21:45 UTC, Ericgacoki requested changes

2021-07-13 21:45 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.md
> +{ "_id" : ObjectId("60db7a59ee65088f9b51677e"), "student_number" : 5, "name" : "Last student added", "age" : 22, "Course" : "Engineering" }
```suggestion
```json
db.students.find() (did time move?)
{ "_id" : ObjectId("60db758c4a433597bcae61c0"), "student_number" : 1, "name" : "John Doe", "age" : 17, "Course" : "Computer Science" }
{ "_id" : ObjectId("60db758c4a433597bcae61c1"), "student_number" : 4, "name" : "John Dohn", "age" : 37, "Course" : "Political Science" }
{ "_id" : ObjectId("60db758c4a433597bcae61c2"), "student_number" : 2, "name" : "Joan Dee", "age" : 23, "Course" : "Computer Animation" }
{ "_id" : ObjectId("60db758c4a433597bcae61c3"), "student_number" : 3, "name" : "Jim Doeh", "age" : 19, "Course" : "Industrial Science" }
{ "_id" : ObjectId("60db7a59ee65088f9b51677e"), "student_number" : 5, "name" : "Last student added", "age" : 22, "Course" : "Engineering" }
```

2021-07-13 21:48 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.md
> +db.students.find()
```suggestion
This command should fetch all objects from the JSON file that was imported as below:
```json
db.students.find() is it long ago?
```

2021-07-28 12:42 UTC, Ericgacoki commented on app/src/main/res/duplicate/Fragment.md
> +```
A good way to represent dependency!

2021-08-01 11:48 UTC, Ericgacoki commented
Closing for inactivity

2021-08-01 11:48 UTC, closed without merging